[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
contracts = "4YJdg3btfUVYP6PZsGLhaJMLaBxFzmM1MWvkS2BYKHPi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/Users/levien/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
